"""
Export trained GomokuCNN weights to C header file for SoC inference.

Quantization: FP32 → int8 (symmetric, per-tensor)
  scale = max(abs(weight)) / 127
  q_weight = round(weight / scale), clamped to [-128, 127]

Output format: C arrays compatible with the NN accelerator.
Weights are packed 4 × int8 per 32-bit word (little-endian).
"""

import torch
import numpy as np
import argparse
import struct
from model import GomokuCNN


def quantize_tensor(tensor, name):
    """Quantize a float32 tensor to int8. Returns (q_data, scale)."""
    t = tensor.detach().cpu().numpy()
    max_val = np.max(np.abs(t))
    if max_val == 0:
        scale = 1.0
    else:
        scale = max_val / 127.0

    q = np.clip(np.round(t / scale), -128, 127).astype(np.int8)
    return q, scale


def pack_int8_to_int32(arr):
    """Pack 4 int8 values into one uint32 (little-endian: byte0, byte1, byte2, byte3)."""
    # Pad to multiple of 4
    padded = np.pad(arr, (0, (4 - len(arr) % 4) % 4), mode='constant', constant_values=0)
    result = []
    for i in range(0, len(padded), 4):
        word = (np.uint8(padded[i]) |
                (np.uint8(padded[i+1]) << 8) |
                (np.uint8(padded[i+2]) << 16) |
                (np.uint8(padded[i+3]) << 24))
        result.append(np.uint32(word))
    return np.array(result, dtype=np.uint32)


def export_to_c_header(model, output_path):
    """Export model weights as a C header file."""
    lines = []
    lines.append("// Auto-generated GomokuCNN weights (int8 quantized)")
    lines.append("// Generated by export_weights.py")
    lines.append(f"// Total parameters: {model.count_parameters():,}")
    lines.append("")
    lines.append("#ifndef NN_WEIGHTS_H")
    lines.append("#define NN_WEIGHTS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Layer configurations
    lines.append("// ============================================")
    lines.append("// Layer configurations")
    lines.append("// ============================================")
    lines.append("")
    lines.append("#define NN_IN_CHANNELS   4")
    lines.append("#define NN_BOARD_SIZE     15")
    lines.append("#define NN_NUM_MOVES      225")
    lines.append("")

    # Quantize and export each layer
    layers = {
        'conv1_weight': (model.conv1.weight, 'conv1'),
        'conv1_bias':   (model.conv1.bias, 'conv1'),
        'conv2_weight': (model.conv2.weight, 'conv2'),
        'conv2_bias':   (model.conv2.bias, 'conv2'),
        'conv3_weight': (model.conv3.weight, 'conv3'),
        'conv3_bias':   (model.conv3.bias, 'conv3'),
        'policy_weight': (model.policy_conv.weight, 'policy'),
        'policy_bias':   (model.policy_conv.bias, 'policy'),
        'value_w1':      (model.value_fc1.weight, 'value_fc1'),
        'value_b1':      (model.value_fc1.bias, 'value_fc1'),
        'value_w2':      (model.value_fc2.weight, 'value_fc2'),
        'value_b2':      (model.value_fc2.bias, 'value_fc2'),
    }

    # Store quantization scales
    scales = {}

    lines.append("// ============================================")
    lines.append("// Quantization scales (float32)")
    lines.append("// ============================================")
    lines.append("")

    for key, (tensor, layer_name) in layers.items():
        q_data, scale = quantize_tensor(tensor, key)
        scales[f"{layer_name}_{'bias' if 'bias' in key else 'weight'}_scale"] = scale
        lines.append(f"// {layer_name}.{key.split('_')[-1]}: scale = {scale:.6f}")

    lines.append("")
    lines.append("// ============================================")
    lines.append("// Quantized weights (int8, packed 4 per uint32)")
    lines.append("// ============================================")
    lines.append("")

    for key, (tensor, layer_name) in layers.items():
        q_data, _ = quantize_tensor(tensor, key)

        # Flatten and pack
        flat = q_data.flatten()
        packed = pack_int8_to_int32(flat)

        var_name = f"nn_{key}"
        lines.append(f"// {layer_name}: shape {list(tensor.shape)}, {len(flat)} int8 values, {len(packed)} words")
        lines.append(f"static const uint32_t {var_name}[] = {{")

        # Print 8 words per line
        for i in range(0, len(packed), 8):
            chunk = packed[i:i+8]
            hex_vals = ", ".join(f"0x{w:08X}" for w in chunk)
            if i + 8 < len(packed):
                lines.append(f"    {hex_vals},")
            else:
                lines.append(f"    {hex_vals}")
        lines.append("};")
        lines.append("")

    # Layer dimension defines
    lines.append("// ============================================")
    lines.append("// Layer dimensions (for accelerator config)")
    lines.append("// ============================================")
    lines.append("")

    w1 = model.conv1.weight
    w2 = model.conv2.weight
    w3 = model.conv3.weight
    pw = model.policy_conv.weight
    vw1 = model.value_fc1.weight
    vw2 = model.value_fc2.weight

    lines.append(f"#define CONV1_OUT_CH {w1.shape[0]}")
    lines.append(f"#define CONV2_OUT_CH {w2.shape[0]}")
    lines.append(f"#define CONV3_OUT_CH {w3.shape[0]}")
    lines.append(f"#define POLICY_OUT_CH {pw.shape[0]}")
    lines.append(f"#define VALUE_FC1_OUT  {vw1.shape[0]}")
    lines.append(f"#define VALUE_FC2_OUT  {vw2.shape[0]}")
    lines.append("")

    lines.append("#endif /* NN_WEIGHTS_H */")

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Exported weights to {output_path}")
    print(f"Total layers: {len(layers)}")
    total_bytes = sum(
        len(pack_int8_to_int32(quantize_tensor(t, _)[0].flatten())) * 4
        for _, (t, _) in layers.items()
    )
    print(f"Total weight data: {total_bytes} bytes")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export GomokuCNN weights to C header")
    parser.add_argument("--checkpoint", type=str, required=True,
                        help="Path to model checkpoint (.pt file)")
    parser.add_argument("--output", type=str, default="nn_weights.h",
                        help="Output C header file path")
    args = parser.parse_args()

    model = GomokuCNN()
    checkpoint = torch.load(args.checkpoint, map_location='cpu')
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()

    export_to_c_header(model, args.output)
